language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

install:
  - npm install

script:
  - npm run ci

before_deploy: npm run build
deploy:
  provider: npm
  email: 343206347@qq.com
  api_key: $NPM_TOKEN
  on:
    tags: true
  tag: latest
